# Generated by Django 4.1.1 on 2022-09-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20220928_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.status'),
        ),
    ]
