# Generated by Django 4.1.1 on 2022-10-08 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0006_auto_20221007_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.AlterField(
            model_name='issues',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
