# Generated by Django 4.1.1 on 2022-10-08 19:39

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "Customer":"A customer, can submit all the issues that he has.",
        "Agent":"An agent can move issues to many status.",
        "Manager":"A managet work as a agent, but h has a major rank"
    }
    Roles = apps.get_model("accounts", "Role")
    for name, desc in entries.items():
        status_obj = Roles(name=name)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [migrations.RunPython(populate_status)]
